### ISSUE TITLE
How to configure contract without signer?

### ISSUE THREAD

**Issue by Rafiq311** [tzztson/simple-infura-transaction#5]
I wonder it has not configure contract without signer.
Without signer is it possible?

**Comment by tzztson** [comment]
As you can see, the wallet  is playing a role like a signer here.
If the private key exists, the contract can be c
![ray-so-export](https://user-images.githubusercontent.com/112578419/214935357-be9cdea5-ce71-4391-aa7e-fa109978c492.png)
onfigured without connecting to the wallet.
